export const ApiService = {
  GET_POPULAR_MOVIES: "/movie/popular",
  GET_NOW_PLAYING_MOVIES: "/movie/now_playing",
  GET_UPCOMING_MOVIES: "/movie/upcoming",
  GET_TOP_RATED_MOVIES: "/movie/top_rated",
  GET_POPULAR_TV_SHOWS: "/tv/popular",
  GET_AIRING_TODAY_TV_SHOWS: "/tv/airing_today",
  GET_ON_THE_AIR_TV_SHOWS: "/tv/on_the_air",
  GET_TOP_RATED_TV_SHOWS: "/tv/top_rated",
  GET_MOVIE_GENERS: "/genre/movie/list",
  GET_TV_SHOW_GENERS: "/genre/tv/list",
  GET_LANGUAGES: "/configuration/languages",
  FILTER_MOVIES: "/discover/movie",
  FILTER_TV_SHOWS: "/discover/tv",
  GET_POPULAR_PERSON: "/person/popular",
  GET_PERSON_DETAILS: "/person",
  GET_COMBINED_CREDITS: "/combined_credits",
  GET_MOVIE_CREDITS: "/movie_credits",
  GET_TV_CREDITS: "/tv_credits",
  GET_EXTERNAL_ID: "/external_ids",
  GET_PERSONAL_IMAGES: "/images",
};
